name: Weekly Maintenance

# Run on schedule and also allow manual trigger
on:
  schedule:
    - cron: "0 9 * * 1"   # every Monday at 09:00 UTC
  workflow_dispatch:       # allows manual runs from the Actions tab

jobs:
  maintenance:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repo (if needed for exomercat)
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install -I .

      # Step 4: Run your maintenance command
      - name: Run exomercat maintenance
        run: |
          output=$(exomercat -v maintenance)
          echo "$output"  
          if echo "$output" | grep -q "FAILED"; then
            echo "Maintenance failed due to 'FAILED' in output"
            exit 1
          fi
